theme: jekyll-theme-minimal
title: Xiaoxu's CV
logo: /assets/img/xiaoxu.png
description: Xiaoxu Li received Master degree and Bachelor degree from University of Science and Technology of China, respectively. He is currently pursuing his Ph.D. degree at the University of Technology Sydney, Sydney, Australia. His research interests focus in computer vision, and machine learning.
#description: Contact Info Tel 0412325801 \n\ Email xiaoxu.li@student.uts.edu.au \n\ Faculty of Engineering and Information Technology | University of Technology Sydney, Australia
#description: Contact Info 
#description: "Tel: 0412325801" 
#description: "Email: xiaoxu.li@student.uts.edu.au" 
#description: Faculty of Engineering and Information Technology 
#description: University of Technology Sydney, Australia
show_downloads: false
google_analytics:
