theme: jekyll-theme-minimal
title: Xiaoxu's CV
logo: /assets/img/xiaoxu.png
description: Contact Info <br> Tel: 0412325801 <br> Email: xiaoxu.li@student.uts.edu.au <br> Faculty of Engineering and Information Technology <br> University of Technology Sydney, Australia
show_downloads: false
google_analytics:
